<?php 
if( $_POST ){
$country  =$_POST['country'];
$states    =$_POST['state'];
$district    =$_POST['district'];
$branch    =$_POST['branch'];
 include 'index.html'; 
/*$url = file_get_contents('http://192.168.0.19:5601/app/kibana#/dashboard/Job-Dashoboard?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(filters:!(('$$hashKey':'object:94','$state':(store:appState),meta:(alias:!n,disabled:!f,index:jobs,key:Branch,negate:!f,value:$branch),query:(match:(Branch:(query:$branch,type:phrase))))),options:(darkTheme:!f),panels:!((col:1,id:Total-Count,panelIndex:4,row:1,size_x:3,size_y:2,type:visualization),(col:4,id:Companywise_Detail,panelIndex:1,row:1,size_x:4,size_y:3,type:visualization),(col:8,id:Departmentwise_Detail,panelIndex:2,row:1,size_x:5,size_y:3,type:visualization),(col:2,id:Tablewise_detail,panelIndex:3,row:4,size_x:10,size_y:2,type:visualization),(col:1,id:Collegewise_detail,panelIndex:5,row:6,size_x:5,size_y:2,type:visualization),(col:6,id:Yearwise_detail,panelIndex:6,row:6,size_x:7,size_y:2,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:'Job%20Dashoboard',uiState:(P-3:(vis:(params:(sort:(columnIndex:1,direction:asc))))))',true);*/
$url="http://192.168.0.19:5601/app/kibana#/dashboard/Job-Dashoboard?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(filters:!(('$$hashKey':'object:94','$state':(store:appState),meta:(alias:!n,disabled:!f,index:jobs,key:Branch,negate:!f,value:$branch),query:(match:(Branch:(query:$branch,type:phrase))))),options:(darkTheme:!f),panels:!((col:1,id:Total-Count,panelIndex:4,row:1,size_x:3,size_y:2,type:visualization),(col:4,id:Companywise_Detail,panelIndex:1,row:1,size_x:4,size_y:3,type:visualization),(col:8,id:Departmentwise_Detail,panelIndex:2,row:1,size_x:5,size_y:3,type:visualization),(col:2,id:Tablewise_detail,panelIndex:3,row:4,size_x:10,size_y:2,type:visualization),(col:1,id:Collegewise_detail,panelIndex:5,row:6,size_x:5,size_y:2,type:visualization),(col:6,id:Yearwise_detail,panelIndex:6,row:6,size_x:7,size_y:2,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:'Job%20Dashoboard',uiState:(P-3:(vis:(params:(sort:(columnIndex:1,direction:asc))))))";
echo
"<iframe src=\"http://192.168.0.19:5601/app/kibana#/dashboard/Job-Dashoboard?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(filters:!(('$$hashKey':'object:94','$state':(store:appState),meta:(alias:!n,disabled:!f,index:jobs,key:Branch,negate:!f,value:$branch),query:(match:(Branch:(query:$branch,type:phrase))))),options:(darkTheme:!f),panels:!((col:1,id:Total-Count,panelIndex:4,row:1,size_x:3,size_y:2,type:visualization),(col:4,id:Companywise_Detail,panelIndex:1,row:1,size_x:4,size_y:3,type:visualization),(col:8,id:Departmentwise_Detail,panelIndex:2,row:1,size_x:5,size_y:3,type:visualization),(col:2,id:Tablewise_detail,panelIndex:3,row:4,size_x:10,size_y:2,type:visualization),(col:1,id:Collegewise_detail,panelIndex:5,row:6,size_x:5,size_y:2,type:visualization),(col:6,id:Yearwise_detail,panelIndex:6,row:6,size_x:7,size_y:2,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:'Job%20Dashoboard',uiState:(P-3:(vis:(params:(sort:(columnIndex:1,direction:asc))))))\" width=100% height=100%></iframe>";
}
?>

